services:
  mosquitto-eclipse:
    image: eclipse-mosquitto:2.0.22
    container_name: mqtt-broker-container
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - dfc_api
  api-server:
    build:
        context: ./api
        dockerfile: Dockerfile
    container_name: dc_server
    ports:
        - "3001:3001"
    develop:
      watch:
        - path: ./api
          action: sync
          target: /home/node/app
          ignore:
            - node_modules/
        - path: ./api/package.json
          action: rebuild
    depends_on:
      - mosquitto-eclipse
    volumes:
      - ${PWD}/api/src/database:/home/node/app/src/database
    networks:
      - dfc_api

networks:
  dfc_api:
          