version: "3.8"

services:
  mosquitto-eclipse:
    image: eclipse-mosquitto:2.0.22
    container_name: mqtt-broker-container
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  api-server:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: dc_server
    depends_on:
      - mosquitto-eclipse
    ports:
      - "3001:3001"
    volumes:
      - ./api/src/database:/home/node/app/src/database
    environment:
      - NODE_ENV=development
      - MQTT_URL=mqtt://mosquitto-eclipse:1883
